FROM alpine:3.12

ENV APP_PATH /project
ENV APP_BIN_PATH "$APP_PATH/bin"
ENV PATH "$PATH:$APP_BIN_PATH"

WORKDIR $APP_PATH

COPY ./bin/install_system_dependencies $APP_BIN_PATH/install_system_dependencies
RUN install_system_dependencies

ENTRYPOINT [ "entrypoint" ]